/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2025-07-09 08:02:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.User;
import model.User;

public final class celebDetail5_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1751616556000L));
    _jspx_dependants.put("jar:file:/C:/teamproject_0708/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookRec_Final/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/css/main_css.jsp", Long.valueOf(1751947096000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1751950996000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

User loggedInUser = (User) session.getAttribute("loggedInUser");
String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/celebList.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/celebDetail.css\" />\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<style>\n");
      out.write("  /* 기본 스타일 (기존 유지) */\n");
      out.write("body {\n");
      out.write("    font-family: 'Arial', sans-serif;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: space-between;\n");
      out.write("    align-items: center;\n");
      out.write("    background-color: #eff7e8;\n");
      out.write("    padding: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#logo img {\n");
      out.write("    width: 200px;\n");
      out.write("    height: auto;\n");
      out.write("    margin-left: 150px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#logo a img {\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-form { /* CSS 클래스 이름 수정 */\n");
      out.write("  display: flex;\n");
      out.write("  justify-content: center;\n");
      out.write("  align-items: center;\n");
      out.write("  gap: 10px;\n");
      out.write("  margin: 10px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#search-box {\n");
      out.write("  padding: 10px;\n");
      out.write("  width: 400px;\n");
      out.write("  font-size: 16px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#search-btn {\n");
      out.write("  padding: 10px 16px;\n");
      out.write("  background-color: #446b3c;\n");
      out.write("  color: white;\n");
      out.write("  border: none;\n");
      out.write("  font-size: 16px;\n");
      out.write("  border-radius: 4px;\n");
      out.write("  cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("#search-btn:hover {\n");
      out.write("    background-color: #cce0b8;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ======================================================== */\n");
      out.write("/* [수정된 부분 시작] 기존 버튼 스타일을 아래 코드로 대체합니다. */\n");
      out.write("/* ======================================================== */\n");
      out.write("\n");
      out.write("/* 회원가입, 로그인 등 기본 버튼 스타일 */\n");
      out.write("#user-buttons button {\n");
      out.write("    display: inline-block;\n");
      out.write("    width: 110px;\n");
      out.write("    height: 42px;\n");
      out.write("    line-height: 42px;\n");
      out.write("    text-align: center;\n");
      out.write("    vertical-align: middle;\n");
      out.write("    white-space: nowrap;\n");
      out.write("    \n");
      out.write("    background-color: #e6f0d7;\n");
      out.write("    color: #446b3c;\n");
      out.write("    border: 1px solid #c0dab0;\n");
      out.write("    border-radius: 4px;\n");
      out.write("    \n");
      out.write("    font-weight: bold;\n");
      out.write("    font-size: 14px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    transition: background-color 0.2s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 마이페이지, 로그아웃 링크를 버튼처럼 보이게 하는 스타일 */\n");
      out.write(".header-action-btn {\n");
      out.write("    display: inline-block;\n");
      out.write("    width: 110px;\n");
      out.write("    height: 42px;\n");
      out.write("    line-height: 42px;\n");
      out.write("    text-align: center;\n");
      out.write("    vertical-align: middle;\n");
      out.write("    white-space: nowrap;\n");
      out.write("    \n");
      out.write("    background-color: #e6f0d7;\n");
      out.write("    color: #446b3c;\n");
      out.write("    border: 1px solid #c0dab0;\n");
      out.write("    border-radius: 4px;\n");
      out.write("    \n");
      out.write("    font-weight: bold;\n");
      out.write("    font-size: 14px;\n");
      out.write("    text-decoration: none; /* a 태그 밑줄 제거 */\n");
      out.write("    cursor: pointer;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    transition: background-color 0.2s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 모든 버튼에 동일한 hover 효과 적용 */\n");
      out.write("#user-buttons button:hover,\n");
      out.write(".header-action-btn:hover {\n");
      out.write("    background-color: #d0e6c5;\n");
      out.write("    border-color: #a9c7a7;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 환영 메시지 텍스트 세로 정렬 */\n");
      out.write(".welcome-message {\n");
      out.write("    vertical-align: middle;\n");
      out.write("    margin-right: 10px;\n");
      out.write("    font-weight: bold;\n");
      out.write("    color: #446b3c;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ======================================================== */\n");
      out.write("/* [수정된 부분 끝]                                        */\n");
      out.write("/* ======================================================== */\n");
      out.write("\n");
      out.write("nav {\n");
      out.write("    background-color: #e6f0d7;\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 15px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav a {\n");
      out.write("    text-decoration: none;\n");
      out.write("    margin: 0 40px;\n");
      out.write("    color: #000;\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav a:hover {\n");
      out.write("    text-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#user-buttons {\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center; /* 버튼과 텍스트 세로 정렬을 위해 추가 */\n");
      out.write("    gap: 10px;\n");
      out.write("    margin-right: 150px;\n");
      out.write("} \n");
      out.write(".banner {\n");
      out.write("    position: relative;\n");
      out.write("    width: 100%;\n");
      out.write("    height: 650px;\n");
      out.write("    overflow: hidden;\n");
      out.write("      background-color: transparent;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".banner img {\n");
      out.write("    position: absolute;\n");
      out.write("    top: 0;\n");
      out.write("    left: 0;\n");
      out.write("    width: 100%;\n");
      out.write("    height: 100%;\n");
      out.write("    object-fit: cover;\n");
      out.write("    object-position: center center;\n");
      out.write("    z-index: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".banner-controls {\n");
      out.write("    position: absolute;\n");
      out.write("    bottom: 10px;\n");
      out.write("    right: 10px;\n");
      out.write("    z-index: 3;\n");
      out.write("    display: flex;\n");
      out.write("    gap: 6px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".banner-controls button {\n");
      out.write("    background-color: rgba(255, 193, 7, 0.9);\n");
      out.write("    border: none;\n");
      out.write("    padding: 6px 8px;\n");
      out.write("    font-size: 14px;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    color: #000;\n");
      out.write("    transition: background-color 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".banner-controls button:hover {\n");
      out.write("    background-color: rgba(255, 160, 0, 0.95);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".section-title {\n");
      out.write("    background-color: #e6f0d7;\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    flex-wrap: wrap;\n");
      out.write("    gap: 34px;\n");
      out.write("    padding: 18px 0;\n");
      out.write("     width: 100%;        /* ✅ 추가 */\n");
      out.write("    margin: 8px 0;      /* ✅ 가운데 정렬 제거 */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".section-title a {\n");
      out.write("    text-decoration: none;\n");
      out.write("    margin: 0 20px;\n");
      out.write("    color: #000;\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".section-title a:hover {\n");
      out.write("    text-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main_list {\n");
      out.write("    padding: 20px;\n");
      out.write("    text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(" .tag-list {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    flex-wrap: wrap;\n");
      out.write("    gap: 12px;\n");
      out.write("    margin: 20px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".tag-button {\n");
      out.write("    background-color: #e6f0d7; /* 기본 연그린 */\n");
      out.write("    border: 1px solid transparent;\n");
      out.write("    padding: 8px 16px;\n");
      out.write("    border-radius: 20px;\n");
      out.write("    font-size: 14px;\n");
      out.write("    color: #446b3c; /* 그린 계열 텍스트 */\n");
      out.write("    cursor: pointer;\n");
      out.write("    font-weight: 600;\n");
      out.write("    transition: background-color 0.3s, color 0.3s, border 0.3s;\n");
      out.write("    outline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".tag-button:hover {\n");
      out.write("    background-color: #d0e6c5;             /* hover 시 약간 더 진한 그린 */\n");
      out.write("    color: #2e4f25;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".tag-button.active {\n");
      out.write("    background-color: #c0dab0;             /* 클릭됐을 때 조금 더 강조 */\n");
      out.write("    border: 1px solid #8cb78a;             /* 테두리도 자연스러운 초록 */\n");
      out.write("    color: #2e4f25;                        /* 글자도 어울리는 진한 그린 */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".tag-button:focus {\n");
      out.write("    outline: none;\n");
      out.write("    box-shadow: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 책 슬라이더 스타일 */\n");
      out.write(".book-carousel {\n");
      out.write("    position: relative;\n");
      out.write("    max-width: 1000px;\n");
      out.write("    margin: 0 auto 40px auto;\n");
      out.write("    overflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".carousel-window {\n");
      out.write("    width: 1000px;\n");
      out.write("    overflow: hidden;\n");
      out.write("    margin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".carousel-track {\n");
      out.write("    display: flex;\n");
      out.write("    transition: transform 0.5s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 이전/다음 버튼 - 위치 고정, 색상 조정 */\n");
      out.write(".carousel-btn {\n");
      out.write("    position: absolute;\n");
      out.write("    top: 50%;\n");
      out.write("    transform: translateY(-50%);\n");
      out.write("    font-size: 26px;\n");
      out.write("    background-color: #f3f8ef;\n");
      out.write("    border: none;\n");
      out.write("    color: #444;\n");
      out.write("    cursor: pointer;\n");
      out.write("    padding: 8px 12px;\n");
      out.write("    border-radius: 50%;\n");
      out.write("    z-index: 2;\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    justify-content: center;\n");
      out.write("    transition: background-color 0.3s, color 0.3s;\n");
      out.write("    user-select: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".carousel-btn:hover {\n");
      out.write("    background-color: #c8dfb5;\n");
      out.write("    color: #000;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".carousel-btn.prev {\n");
      out.write("    left: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".carousel-btn.next {\n");
      out.write("    right: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".book-item {\n");
      out.write("    flex: 0 0 25%;\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 10px;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".book-item img {\n");
      out.write("    width: 180px;\n");
      out.write("    height: 260px;\n");
      out.write("    object-fit: cover;\n");
      out.write("    border-radius: 6px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".book-info {\n");
      out.write("    margin-top: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".book-title {\n");
      out.write("    font-size: 14px;\n");
      out.write("    font-weight: bold;\n");
      out.write("    margin-top: 10px;\n");
      out.write("    color: #444;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".book-author {\n");
      out.write("    font-size: 12px;\n");
      out.write("    color: #666;\n");
      out.write("}\n");
      out.write("\n");
      out.write("footer {\n");
      out.write("    background-color: #eff7e8;\n");
      out.write("    color: #333;\n");
      out.write("    padding: 20px 0;\n");
      out.write("    text-align: center;\n");
      out.write("    font-size: 14px;\n");
      out.write("    border-top: 1px solid #ccc;\n");
      out.write("    margin-top: 60px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-container {\n");
      out.write("    max-width: 1000px;\n");
      out.write("    margin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-links a {\n");
      out.write("    color: #333;\n");
      out.write("    text-decoration: none;\n");
      out.write("    margin: 0 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-links a:hover {\n");
      out.write("    text-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write(" /* 이전/다음 버튼 스타일 */\n");
      out.write("#carousel-prev-btn, #carousel-next-btn {\n");
      out.write("    font-size: 18px;\n");
      out.write("    padding: 5px 12px;\n");
      out.write("    margin: 10px 5px 20px 5px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    border: 1px solid #446b3c;\n");
      out.write("    background: white;\n");
      out.write("    color: #446b3c;\n");
      out.write("    border-radius: 4px;\n");
      out.write("}\n");
      out.write("#carousel-prev-btn:hover, #carousel-next-btn:hover {\n");
      out.write("    background-color: #446b3c;\n");
      out.write("    color: white;\n");
      out.write("}\n");
      out.write("#scrollToTopBtn {\n");
      out.write("  position: fixed;\n");
      out.write("  bottom: 150px;\n");
      out.write("  right: 40px;\n");
      out.write("  width: 66px; /* 이미지와 딱 맞게 약간 키움 */\n");
      out.write("  height: 66px;\n");
      out.write("  background-color: transparent;\n");
      out.write("  border: none;\n");
      out.write("  border-radius: 0;\n");
      out.write("  transform: rotate(45deg);\n");
      out.write("  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15); /* 그림자 더 작고 약하게 */\n");
      out.write("  cursor: pointer;\n");
      out.write("  display: flex;\n");
      out.write("  justify-content: center;\n");
      out.write("  align-items: center;\n");
      out.write("  z-index: 999;\n");
      out.write("  transition: all 0.3s ease;\n");
      out.write("  backdrop-filter: blur(10px);\n");
      out.write("  padding: 0;\n");
      out.write("  margin-top: 0px; /* margin-top 제거 또는 0으로 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#scrollToTopBtn img {\n");
      out.write("  width: 100%;\n");
      out.write("  height: 100%;\n");
      out.write("  object-fit: contain;\n");
      out.write("  transform: rotate(-45deg);\n");
      out.write("  display: block;\n");
      out.write("  transition: transform 0.3s ease;\n");
      out.write("  position: relative;\n");
      out.write("  top: 0;\n");
      out.write("  left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#scrollToTopBtn:hover {\n");
      out.write("  transform: rotate(45deg) translateY(2px); /* 움직임도 줄임 */\n");
      out.write("  box-shadow: 0 6px 10px rgba(0, 0, 0, 0.2); /* 호버시 그림자도 작게 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#scrollToTopBtn:hover img {\n");
      out.write("  transform: scale(1.05) rotate(-45deg);\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"img/icon2.png\" type=\"image/x-icon\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>박정민의 추천 책</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" />\r\n");
      out.write("	<link rel=\"icon\" href=\"img/icon2.png\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div id=\"logo\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.jsp\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/img/logo.png\" alt=\"로고\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"search-form\">\r\n");
      out.write("        <input type=\"text\" id=\"search-box\" placeholder=\"검색어를 입력하세요...\" class=\"search-input\" />\r\n");
      out.write("        <button type=\"button\" id=\"search-btn\" class=\"search-button\">검색</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"user-buttons\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
 if (session.getAttribute("loggedInUser") == null) { 
      out.write("\r\n");
      out.write("            <button id=\"join-btn\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/register.jsp'\">회원가입</button>\r\n");
      out.write("            <button id=\"login-btn\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/login.jsp'\">로그인</button>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            ");
 User tempUser = (User) session.getAttribute("loggedInUser"); 
      out.write("\r\n");
      out.write("            <span class=\"welcome-message\">환영합니다, ");
      out.print( tempUser.getNickname() );
      out.write("님!</span>\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/mypage.jsp\" class=\"header-action-btn\">마이페이지</a>\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/doLogout\" class=\"header-action-btn\" onclick=\"return confirm('정말 로그아웃 하시겠습니까?');\">로그아웃</a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<nav>\r\n");
      out.write("		<a href=\"");
      out.print(contextPath);
      out.write("/aiRecommend.jsp\">(AI) 책 추천</a> <a\r\n");
      out.write("			href=\"");
      out.print(contextPath);
      out.write("/reviewList.jsp\">리뷰</a> <a\r\n");
      out.write("			href=\"");
      out.print(contextPath);
      out.write("/playlistmain.jsp\">플레이리스트</a> <a\r\n");
      out.write("			href=\"");
      out.print(contextPath);
      out.write("/celebList.jsp\">셀럽추천</a> <a\r\n");
      out.write("			href=\"");
      out.print(contextPath);
      out.write("/mypage.jsp\">마이페이지</a>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h1>박정민</h1>\r\n");
      out.write("		<p class=\"desc\">출판사 '무제'대표 박정민의 책장</p>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"thumbnail-container\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin_thum.jpg\" alt=\"Celeb2 이미지\" />\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"text-block\">\"작가는 아니다. 글씨만 쓸줄 아는 그저 평범한 당신의 옆집 남자. 가끔 텔레비전이나 영화에 나오기도 한다.\"</div>\r\n");
      out.write("		<div class=\"text-block\">\"언젠가는 나도 각도 큰 변화구를 던져볼 수 있을 거다. 여러분도 적절히 변화구도 섞어가면서 살아가시길 바란다.\"</div>\r\n");
      out.write("		<div class=\"text-block\">\"원래 사람들은 바쁘거나 노는 게 더 좋아서 책을 안 읽잖아요. 그러니까 책 읽기 캠페인 같은 걸 하겠죠. \r\n");
      out.write("		책을 만드는 건, 뭘 좀 재밌게 만들어보고 싶은데 제가 책을 좋아하고 (책을 만드는 데) 돈이 덜 들잖아요. 영화는 혼자 만들 수 없으니까요. \r\n");
      out.write("		책으로 돈을 벌려는 게 아니라 오히려 돈을 더 써서, 예술적이고 고급스런 물성을 갖게 하려는 게 지향점이에요.\"\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"img-block\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin01.png\" alt=\"책 이미지 1\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"book-card\" onclick=\"window.open('https://product.kyobobook.co.kr/detail/S000001945337', '_blank')\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin_book01.jpg\" alt=\"책1\">\r\n");
      out.write("			<div class=\"book-info\">\r\n");
      out.write("				<div class=\"book-title\">사물의 뒷모습</div>\r\n");
      out.write("				<p class=\"book-meta\">저자: 안규철</p>\r\n");
      out.write("				<p class=\"book-meta\">출판: 현대문학</p>\r\n");
      out.write("				<p class=\"book-meta\">발매: 2021.03.19</p>\r\n");
      out.write("				<p class=\"book-desc\">안규철의 내 이야기로 그린 그림, 그 두 번째 이야기</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"img-block\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin02.png\" alt=\"책 이미지 2\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"book-card\" onclick=\"window.open('https://product.kyobobook.co.kr/detail/S000000569720', '_blank')\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin_book02.jpg\" alt=\"책2\">\r\n");
      out.write("			<div class=\"book-info\">\r\n");
      out.write("				<div class=\"book-title\">사유 속의 영화</div>\r\n");
      out.write("				<p class=\"book-meta\">저자: 이윤영</p>\r\n");
      out.write("				<p class=\"book-meta\">출판: 문학과지성사</p>\r\n");
      out.write("				<p class=\"book-meta\">발매: 2011.04.18</p>\r\n");
      out.write("				<p class=\"book-desc\">영화 이론 선집 |</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"img-block\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin03.png\" alt=\"책 이미지 3\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"book-card\" onclick=\"window.open('https://product.kyobobook.co.kr/detail/S000000780415', '_blank')\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin_book03.jpg\" alt=\"책3\">\r\n");
      out.write("			<div class=\"book-info\">\r\n");
      out.write("				<div class=\"book-title\">아침 그리고 저녁</div>\r\n");
      out.write("				<p class=\"book-meta\">저자: 욘 포세라</p>\r\n");
      out.write("				<p class=\"book-meta\">출판: 문학동네</p>\r\n");
      out.write("				<p class=\"book-meta\">발매: 2019.07.26</p>\r\n");
      out.write("				<p class=\"book-desc\">시적이고 음악적인 문체로 묘파하는 인간의 삶과 생존투쟁, 그리고 죽음</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"img-block\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin04.png\" alt=\"책 이미지 4\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"book-card\" onclick=\"window.open('https://product.kyobobook.co.kr/detail/S000061353843', '_blank')\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin_book04.jpg\" alt=\"책4\">\r\n");
      out.write("			<div class=\"book-info\">\r\n");
      out.write("				<div class=\"book-title\">나는 나를 파괴할 권리가 있다</div>\r\n");
      out.write("				<p class=\"book-meta\">저자: 김영하</p>\r\n");
      out.write("				<p class=\"book-meta\">출판: 복복서가</p>\r\n");
      out.write("				<p class=\"book-meta\">발매: 2022.05.23</p>\r\n");
      out.write("				<p class=\"book-desc\">『나는 나를 파괴할 권리가 있다』 개정판</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"img-block\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin05.png\" alt=\"책 이미지 5\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"book-card\" onclick=\"window.open('https://product.kyobobook.co.kr/detail/S000216111714', '_blank')\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin_book05.jpg\" alt=\"책5\">\r\n");
      out.write("			<div class=\"book-info\">\r\n");
      out.write("				<div class=\"book-title\">혼모노</div>\r\n");
      out.write("				<p class=\"book-meta\">저자: 성해나</p>\r\n");
      out.write("				<p class=\"book-meta\">출판: 창비</p>\r\n");
      out.write("				<p class=\"book-meta\">발매: 2025.03.28</p>\r\n");
      out.write("				<p class=\"book-desc\">무엇이 진짜이고 무엇이 가짜인가 그 경계에서 ‘혼모노’를 묻다\r\n");
      out.write("</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"img-block\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin06.png\" alt=\"책 이미지 6\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"book-card\" onclick=\"window.open('https://product.kyobobook.co.kr/detail/S000000887679', '_blank')\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin_book06.jpg\" alt=\"책6\">\r\n");
      out.write("			<div class=\"book-info\">\r\n");
      out.write("				<div class=\"book-title\">죽은 왕녀를 위한 파반느</div>\r\n");
      out.write("				<p class=\"book-meta\">저자: 박민규</p>\r\n");
      out.write("				<p class=\"book-meta\">출판: 위즈덤하우스</p>\r\n");
      out.write("				<p class=\"book-meta\">발매: 2009.07.20</p>\r\n");
      out.write("				<p class=\"book-desc\">더욱 섬세하고 예리해진 무규칙이종소설가의 리얼 로맨틱 귀환!</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"img-block\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin07.png\" alt=\"책 이미지 7\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"book-card\" onclick=\"window.open('https://product.kyobobook.co.kr/detail/S000000938918', '_blank')\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin_book07.jpg\" alt=\"책7\">\r\n");
      out.write("			<div class=\"book-info\">\r\n");
      out.write("				<div class=\"book-title\">웬만해선 아무렇지 않다</div>\r\n");
      out.write("				<p class=\"book-meta\">저자: 이기호</p>\r\n");
      out.write("				<p class=\"book-meta\">출판: 마음산책</p>\r\n");
      out.write("				<p class=\"book-meta\">발매: 2016.02.25</p>\r\n");
      out.write("				<p class=\"book-desc\">웃음과 눈물의 절묘함 특별한 짧은 소설</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"img-block\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin08.png\" alt=\"책 이미지 8\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"book-card\" onclick=\"window.open('https://product.kyobobook.co.kr/detail/S000213662853', '_blank')\">\r\n");
      out.write("			<img src=\"./img/celeb/parkjungmin_book08.jpg\" alt=\"책8\">\r\n");
      out.write("			<div class=\"book-info\">\r\n");
      out.write("				<div class=\"book-title\">음악소설집</div>\r\n");
      out.write("				<p class=\"book-meta\">저자: 김애란 , 김연수 , 윤성희 , 은희경 , 편혜영 </p>\r\n");
      out.write("				<p class=\"book-meta\">출판: 프란츠</p>\r\n");
      out.write("				<p class=\"book-meta\">발매: 2024.07.01</p>\r\n");
      out.write("				<p class=\"book-desc\">우리 삶의 장면 속엔 늘 음악이 있었다</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 필요한 만큼 image + book-card 반복 -->\r\n");
      out.write("\r\n");
      out.write("		<button class=\"back-btn\" onclick=\"history.back()\">← 뒤로가기</button>\r\n");
      out.write("	</div>\r\n");
      out.write("<button id=\"scrollToTopBtn\">\r\n");
      out.write("  <img src=\"img/up1.png\" alt=\"위로 가기 버튼\" />\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"footer-container\">\r\n");
      out.write("			<p>&copy; 2025 WITHUS. All rights reserved.</p>\r\n");
      out.write("			<div class=\"footer-links\">\r\n");
      out.write("				<a href=\"#\">이용약관</a> | <a href=\"#\">개인정보처리방침</a> | <a href=\"#\">고객센터</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	\r\n");
      out.write("<script>\r\n");
      out.write("	document.addEventListener(\"DOMContentLoaded\", () => {\r\n");
      out.write("		document.getElementById(\"scrollToTopBtn\").addEventListener(\"click\", () => {\r\n");
      out.write("			window.scrollTo({ top: 0, behavior: 'smooth' });\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
