/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2025-07-08 08:13:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.User;
import model.User;

public final class celebForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/css/main_css.jsp", Long.valueOf(1751947096000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1751950996000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

User loggedInUser = (User) session.getAttribute("loggedInUser");
String contextPath = request.getContextPath();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/celebList.css\" />\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<style>\n");
      out.write("  /* 기본 스타일 (기존 유지) */\n");
      out.write("body {\n");
      out.write("    font-family: 'Arial', sans-serif;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    background-color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: space-between;\n");
      out.write("    align-items: center;\n");
      out.write("    background-color: #eff7e8;\n");
      out.write("    padding: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#logo img {\n");
      out.write("    width: 200px;\n");
      out.write("    height: auto;\n");
      out.write("    margin-left: 150px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#logo a img {\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".search-form { /* CSS 클래스 이름 수정 */\n");
      out.write("  display: flex;\n");
      out.write("  justify-content: center;\n");
      out.write("  align-items: center;\n");
      out.write("  gap: 10px;\n");
      out.write("  margin: 10px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#search-box {\n");
      out.write("  padding: 10px;\n");
      out.write("  width: 400px;\n");
      out.write("  font-size: 16px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#search-btn {\n");
      out.write("  padding: 10px 16px;\n");
      out.write("  background-color: #446b3c;\n");
      out.write("  color: white;\n");
      out.write("  border: none;\n");
      out.write("  font-size: 16px;\n");
      out.write("  border-radius: 4px;\n");
      out.write("  cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("#search-btn:hover {\n");
      out.write("    background-color: #cce0b8;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ======================================================== */\n");
      out.write("/* [수정된 부분 시작] 기존 버튼 스타일을 아래 코드로 대체합니다. */\n");
      out.write("/* ======================================================== */\n");
      out.write("\n");
      out.write("/* 회원가입, 로그인 등 기본 버튼 스타일 */\n");
      out.write("#user-buttons button {\n");
      out.write("    display: inline-block;\n");
      out.write("    width: 110px;\n");
      out.write("    height: 42px;\n");
      out.write("    line-height: 42px;\n");
      out.write("    text-align: center;\n");
      out.write("    vertical-align: middle;\n");
      out.write("    white-space: nowrap;\n");
      out.write("    \n");
      out.write("    background-color: #e6f0d7;\n");
      out.write("    color: #446b3c;\n");
      out.write("    border: 1px solid #c0dab0;\n");
      out.write("    border-radius: 4px;\n");
      out.write("    \n");
      out.write("    font-weight: bold;\n");
      out.write("    font-size: 14px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    transition: background-color 0.2s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 마이페이지, 로그아웃 링크를 버튼처럼 보이게 하는 스타일 */\n");
      out.write(".header-action-btn {\n");
      out.write("    display: inline-block;\n");
      out.write("    width: 110px;\n");
      out.write("    height: 42px;\n");
      out.write("    line-height: 42px;\n");
      out.write("    text-align: center;\n");
      out.write("    vertical-align: middle;\n");
      out.write("    white-space: nowrap;\n");
      out.write("    \n");
      out.write("    background-color: #e6f0d7;\n");
      out.write("    color: #446b3c;\n");
      out.write("    border: 1px solid #c0dab0;\n");
      out.write("    border-radius: 4px;\n");
      out.write("    \n");
      out.write("    font-weight: bold;\n");
      out.write("    font-size: 14px;\n");
      out.write("    text-decoration: none; /* a 태그 밑줄 제거 */\n");
      out.write("    cursor: pointer;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    transition: background-color 0.2s;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 모든 버튼에 동일한 hover 효과 적용 */\n");
      out.write("#user-buttons button:hover,\n");
      out.write(".header-action-btn:hover {\n");
      out.write("    background-color: #d0e6c5;\n");
      out.write("    border-color: #a9c7a7;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 환영 메시지 텍스트 세로 정렬 */\n");
      out.write(".welcome-message {\n");
      out.write("    vertical-align: middle;\n");
      out.write("    margin-right: 10px;\n");
      out.write("    font-weight: bold;\n");
      out.write("    color: #446b3c;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* ======================================================== */\n");
      out.write("/* [수정된 부분 끝]                                        */\n");
      out.write("/* ======================================================== */\n");
      out.write("\n");
      out.write("nav {\n");
      out.write("    background-color: #e6f0d7;\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 15px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav a {\n");
      out.write("    text-decoration: none;\n");
      out.write("    margin: 0 40px;\n");
      out.write("    color: #000;\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav a:hover {\n");
      out.write("    text-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#user-buttons {\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center; /* 버튼과 텍스트 세로 정렬을 위해 추가 */\n");
      out.write("    gap: 10px;\n");
      out.write("    margin-right: 150px;\n");
      out.write("} \n");
      out.write(".banner {\n");
      out.write("    position: relative;\n");
      out.write("    width: 100%;\n");
      out.write("    height: 650px;\n");
      out.write("    overflow: hidden;\n");
      out.write("      background-color: transparent;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".banner img {\n");
      out.write("    position: absolute;\n");
      out.write("    top: 0;\n");
      out.write("    left: 0;\n");
      out.write("    width: 100%;\n");
      out.write("    height: 100%;\n");
      out.write("    object-fit: cover;\n");
      out.write("    object-position: center center;\n");
      out.write("    z-index: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".banner-controls {\n");
      out.write("    position: absolute;\n");
      out.write("    bottom: 10px;\n");
      out.write("    right: 10px;\n");
      out.write("    z-index: 3;\n");
      out.write("    display: flex;\n");
      out.write("    gap: 6px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".banner-controls button {\n");
      out.write("    background-color: rgba(255, 193, 7, 0.9);\n");
      out.write("    border: none;\n");
      out.write("    padding: 6px 8px;\n");
      out.write("    font-size: 14px;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    color: #000;\n");
      out.write("    transition: background-color 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".banner-controls button:hover {\n");
      out.write("    background-color: rgba(255, 160, 0, 0.95);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".section-title {\n");
      out.write("    background-color: #e6f0d7;\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    flex-wrap: wrap;\n");
      out.write("    gap: 34px;\n");
      out.write("    padding: 18px 0;\n");
      out.write("     width: 100%;        /* ✅ 추가 */\n");
      out.write("    margin: 8px 0;      /* ✅ 가운데 정렬 제거 */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".section-title a {\n");
      out.write("    text-decoration: none;\n");
      out.write("    margin: 0 20px;\n");
      out.write("    color: #000;\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".section-title a:hover {\n");
      out.write("    text-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main_list {\n");
      out.write("    padding: 20px;\n");
      out.write("    text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(" .tag-list {\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    flex-wrap: wrap;\n");
      out.write("    gap: 12px;\n");
      out.write("    margin: 20px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".tag-button {\n");
      out.write("    background-color: #e6f0d7; /* 기본 연그린 */\n");
      out.write("    border: 1px solid transparent;\n");
      out.write("    padding: 8px 16px;\n");
      out.write("    border-radius: 20px;\n");
      out.write("    font-size: 14px;\n");
      out.write("    color: #446b3c; /* 그린 계열 텍스트 */\n");
      out.write("    cursor: pointer;\n");
      out.write("    font-weight: 600;\n");
      out.write("    transition: background-color 0.3s, color 0.3s, border 0.3s;\n");
      out.write("    outline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".tag-button:hover {\n");
      out.write("    background-color: #d0e6c5;             /* hover 시 약간 더 진한 그린 */\n");
      out.write("    color: #2e4f25;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".tag-button.active {\n");
      out.write("    background-color: #c0dab0;             /* 클릭됐을 때 조금 더 강조 */\n");
      out.write("    border: 1px solid #8cb78a;             /* 테두리도 자연스러운 초록 */\n");
      out.write("    color: #2e4f25;                        /* 글자도 어울리는 진한 그린 */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".tag-button:focus {\n");
      out.write("    outline: none;\n");
      out.write("    box-shadow: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 책 슬라이더 스타일 */\n");
      out.write(".book-carousel {\n");
      out.write("    position: relative;\n");
      out.write("    max-width: 1000px;\n");
      out.write("    margin: 0 auto 40px auto;\n");
      out.write("    overflow: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".carousel-window {\n");
      out.write("    width: 1000px;\n");
      out.write("    overflow: hidden;\n");
      out.write("    margin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".carousel-track {\n");
      out.write("    display: flex;\n");
      out.write("    transition: transform 0.5s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 이전/다음 버튼 - 위치 고정, 색상 조정 */\n");
      out.write(".carousel-btn {\n");
      out.write("    position: absolute;\n");
      out.write("    top: 50%;\n");
      out.write("    transform: translateY(-50%);\n");
      out.write("    font-size: 26px;\n");
      out.write("    background-color: #f3f8ef;\n");
      out.write("    border: none;\n");
      out.write("    color: #444;\n");
      out.write("    cursor: pointer;\n");
      out.write("    padding: 8px 12px;\n");
      out.write("    border-radius: 50%;\n");
      out.write("    z-index: 2;\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    justify-content: center;\n");
      out.write("    transition: background-color 0.3s, color 0.3s;\n");
      out.write("    user-select: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".carousel-btn:hover {\n");
      out.write("    background-color: #c8dfb5;\n");
      out.write("    color: #000;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".carousel-btn.prev {\n");
      out.write("    left: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".carousel-btn.next {\n");
      out.write("    right: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".book-item {\n");
      out.write("    flex: 0 0 25%;\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 10px;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".book-item img {\n");
      out.write("    width: 180px;\n");
      out.write("    height: 260px;\n");
      out.write("    object-fit: cover;\n");
      out.write("    border-radius: 6px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".book-info {\n");
      out.write("    margin-top: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".book-title {\n");
      out.write("    font-size: 14px;\n");
      out.write("    font-weight: bold;\n");
      out.write("    margin-top: 10px;\n");
      out.write("    color: #444;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".book-author {\n");
      out.write("    font-size: 12px;\n");
      out.write("    color: #666;\n");
      out.write("}\n");
      out.write("\n");
      out.write("footer {\n");
      out.write("    background-color: #eff7e8;\n");
      out.write("    color: #333;\n");
      out.write("    padding: 20px 0;\n");
      out.write("    text-align: center;\n");
      out.write("    font-size: 14px;\n");
      out.write("    border-top: 1px solid #ccc;\n");
      out.write("    margin-top: 60px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-container {\n");
      out.write("    max-width: 1000px;\n");
      out.write("    margin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-links a {\n");
      out.write("    color: #333;\n");
      out.write("    text-decoration: none;\n");
      out.write("    margin: 0 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".footer-links a:hover {\n");
      out.write("    text-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write(" /* 이전/다음 버튼 스타일 */\n");
      out.write("#carousel-prev-btn, #carousel-next-btn {\n");
      out.write("    font-size: 18px;\n");
      out.write("    padding: 5px 12px;\n");
      out.write("    margin: 10px 5px 20px 5px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    border: 1px solid #446b3c;\n");
      out.write("    background: white;\n");
      out.write("    color: #446b3c;\n");
      out.write("    border-radius: 4px;\n");
      out.write("}\n");
      out.write("#carousel-prev-btn:hover, #carousel-next-btn:hover {\n");
      out.write("    background-color: #446b3c;\n");
      out.write("    color: white;\n");
      out.write("}\n");
      out.write("#scrollToTopBtn {\n");
      out.write("  position: fixed;\n");
      out.write("  bottom: 150px;\n");
      out.write("  right: 40px;\n");
      out.write("  width: 66px; /* 이미지와 딱 맞게 약간 키움 */\n");
      out.write("  height: 66px;\n");
      out.write("  background-color: transparent;\n");
      out.write("  border: none;\n");
      out.write("  border-radius: 0;\n");
      out.write("  transform: rotate(45deg);\n");
      out.write("  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15); /* 그림자 더 작고 약하게 */\n");
      out.write("  cursor: pointer;\n");
      out.write("  display: flex;\n");
      out.write("  justify-content: center;\n");
      out.write("  align-items: center;\n");
      out.write("  z-index: 999;\n");
      out.write("  transition: all 0.3s ease;\n");
      out.write("  backdrop-filter: blur(10px);\n");
      out.write("  padding: 0;\n");
      out.write("  margin-top: 0px; /* margin-top 제거 또는 0으로 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#scrollToTopBtn img {\n");
      out.write("  width: 100%;\n");
      out.write("  height: 100%;\n");
      out.write("  object-fit: contain;\n");
      out.write("  transform: rotate(-45deg);\n");
      out.write("  display: block;\n");
      out.write("  transition: transform 0.3s ease;\n");
      out.write("  position: relative;\n");
      out.write("  top: 0;\n");
      out.write("  left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#scrollToTopBtn:hover {\n");
      out.write("  transform: rotate(45deg) translateY(2px); /* 움직임도 줄임 */\n");
      out.write("  box-shadow: 0 6px 10px rgba(0, 0, 0, 0.2); /* 호버시 그림자도 작게 */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#scrollToTopBtn:hover img {\n");
      out.write("  transform: scale(1.05) rotate(-45deg);\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<link rel=\"icon\" href=\"img/icon2.png\" type=\"image/x-icon\">\n");
      out.write("<head>\n");
      out.write("<title>게시글 작성</title>\n");
      out.write("<style>\n");
      out.write("/* 기존 스타일은 유지 */\n");
      out.write("body {\n");
      out.write("	font-family: 'Arial', sans-serif;\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("	background-color: #fff;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("	max-width: 1000px;\n");
      out.write("	margin: 30px auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h2 {\n");
      out.write("	margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"text\"], input[type=\"file\"], textarea {\n");
      out.write("	width: 100%;\n");
      out.write("	padding: 10px;\n");
      out.write("	margin-top: 8px;\n");
      out.write("	margin-bottom: 16px;\n");
      out.write("	border: 1px solid #ccc;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	font-size: 1rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".editor-block {\n");
      out.write("	width: 100%;\n");
      out.write("	border: 1px solid #ddd;\n");
      out.write("	padding: 12px;\n");
      out.write("	border-radius: 8px;\n");
      out.write("	margin-bottom: 12px;\n");
      out.write("	background-color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".editor-block textarea {\n");
      out.write("	resize: vertical;\n");
      out.write("	min-height: 80px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".editor-block input[type=\"file\"] {\n");
      out.write("	background-color: #f4f4f4;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button-box {\n");
      out.write("	text-align: center;\n");
      out.write("	margin-top: 24px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button-box button {\n");
      out.write("	padding: 10px 20px;\n");
      out.write("	font-size: 1rem;\n");
      out.write("	border: none;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	margin-left: 10px;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".submit-btn {\n");
      out.write("	background-color: #e6f0d7;\n");
      out.write("	color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".cancel-btn {\n");
      out.write("	background-color: #fff;\n");
      out.write("	color: black;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".add-block-btn {\n");
      out.write("	display: block;\n");
      out.write("	margin: 0 auto 20px;\n");
      out.write("	padding: 8px 16px;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	background-color: #fff;\n");
      out.write("	color: black;\n");
      out.write("	border: none;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#response-message { /* 응답 메시지 표시 영역 추가 */\n");
      out.write("	color: green;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin-top: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#error-message { /* 오류 메시지 표시 영역 추가 */\n");
      out.write("	color: #d9534f;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin-top: 15px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <div id=\"logo\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/main.jsp\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/img/logo.png\" alt=\"로고\">\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"search-form\">\r\n");
      out.write("        <input type=\"text\" id=\"search-box\" placeholder=\"검색어를 입력하세요...\" class=\"search-input\" />\r\n");
      out.write("        <button type=\"button\" id=\"search-btn\" class=\"search-button\">검색</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"user-buttons\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
 if (session.getAttribute("loggedInUser") == null) { 
      out.write("\r\n");
      out.write("            <button id=\"join-btn\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/register.jsp'\">회원가입</button>\r\n");
      out.write("            <button id=\"login-btn\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/login.jsp'\">로그인</button>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            ");
 User tempUser = (User) session.getAttribute("loggedInUser"); 
      out.write("\r\n");
      out.write("            <span class=\"welcome-message\">환영합니다, ");
      out.print( tempUser.getNickname() );
      out.write("님!</span>\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/mypage.jsp\" class=\"header-action-btn\">마이페이지</a>\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/doLogout\" class=\"header-action-btn\" onclick=\"return confirm('정말 로그아웃 하시겠습니까?');\">로그아웃</a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\n");
      out.write("\n");
      out.write("	<nav>\n");
      out.write("		<a href=\"");
      out.print(contextPath);
      out.write("/aiRecommend.jsp\">(AI) 책 추천</a> <a\n");
      out.write("			href=\"");
      out.print(contextPath);
      out.write("/reviewList\">리뷰</a> <a\n");
      out.write("			href=\"");
      out.print(contextPath);
      out.write("/playlist.jsp\">플레이리스트</a> <a\n");
      out.write("			href=\"");
      out.print(contextPath);
      out.write("/celebList\">셀럽추천</a> <a\n");
      out.write("			href=\"");
      out.print(contextPath);
      out.write("/mypage.jsp\">마이페이지</a>\n");
      out.write("	</nav>\n");
      out.write("	<div class=\"container\">\n");
      out.write("\n");
      out.write("		<h2>셀럽 추천 글 작성</h2>\n");
      out.write("\n");
      out.write("		<form id=\"celebForm\" enctype=\"multipart/form-data\">\n");
      out.write("			");
      out.write("\n");
      out.write("			<label>이름</label> <input type=\"text\" name=\"celebName\" required>\n");
      out.write("			<label>설명</label><input type=\"text\" name=\"celebDescription\" required>\n");
      out.write("			<label>썸네일 이미지</label> <input type=\"file\" name=\"thumbnail\"\n");
      out.write("				accept=\"image/*\">\n");
      out.write("\n");
      out.write("			<div id=\"editor-area\">\n");
      out.write("				<div class=\"editor-block\">\n");
      out.write("					<label>텍스트 입력</label>\n");
      out.write("					<textarea name=\"contentBlock1_text\"></textarea>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div style=\"text-align: center; margin-bottom: 20px;\">\n");
      out.write("				<button type=\"button\" class=\"add-block-btn\"\n");
      out.write("					onclick=\"addEditorBlock('text')\">+ 텍스트 블록 추가</button>\n");
      out.write("				<button type=\"button\" class=\"add-block-btn\"\n");
      out.write("					onclick=\"addEditorBlock('image')\">+ 이미지 블록 추가</button>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("			<div class=\"button-box\">\n");
      out.write("				<button type=\"submit\" class=\"submit-btn\">작성하기</button>\n");
      out.write("				");
      out.write("\n");
      out.write("				<button type=\"button\" class=\"cancel-btn\" onclick=\"history.back()\">취소</button>\n");
      out.write("			</div>\n");
      out.write("		</form>\n");
      out.write("		<div id=\"response-message\"></div>\n");
      out.write("		");
      out.write("\n");
      out.write("		<div id=\"error-message\"></div>\n");
      out.write("		");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<script>\n");
      out.write("    let blockCount = 1;\n");
      out.write("\n");
      out.write("    function addEditorBlock(type) {\n");
      out.write("        blockCount++;\n");
      out.write("        const editorArea = document.getElementById(\"editor-area\");\n");
      out.write("\n");
      out.write("        const blockDiv = document.createElement(\"div\");\n");
      out.write("        blockDiv.className = \"editor-block\";\n");
      out.write("\n");
      out.write("        if (type === \"text\") {\n");
      out.write("            blockDiv.innerHTML = `\n");
      out.write("                <label>텍스트 입력</label>\n");
      out.write("                <textarea name=\"contentBlock");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${blockCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_text\"></textarea>\n");
      out.write("            `;\n");
      out.write("        } else if (type === \"image\") {\n");
      out.write("            blockDiv.innerHTML = `\n");
      out.write("                <label>이미지 업로드</label>\n");
      out.write("                <input type=\"file\" name=\"contentBlock");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${blockCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_image\" accept=\"image/*\">\n");
      out.write("            `;\n");
      out.write("        } else {\n");
      out.write("            alert(\"알 수 없는 블록 타입입니다.\");\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        editorArea.appendChild(blockDiv);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    document.getElementById('celebForm').addEventListener('submit', async function(event) {\n");
      out.write("        event.preventDefault(); // 폼의 기본 제출 동작(새로고침) 방지\n");
      out.write("\n");
      out.write("        const form = event.target;\n");
      out.write("        const formData = new FormData(form); // 파일과 텍스트를 모두 포함하는 FormData 객체 생성\n");
      out.write("\n");
      out.write("        const responseMessageDiv = document.getElementById('response-message');\n");
      out.write("        const errorMessageDiv = document.getElementById('error-message');\n");
      out.write("        responseMessageDiv.textContent = ''; // 메시지 초기화\n");
      out.write("        errorMessageDiv.textContent = ''; // 메시지 초기화\n");
      out.write("\n");
      out.write("        try {\n");
      out.write("            const response = await fetch('api/celeb/recommendations', { // Servlet API 엔드포인트\n");
      out.write("                method: 'POST',\n");
      out.write("                // FormData를 사용할 때는 'Content-Type' 헤더를 명시적으로 설정하지 않습니다.\n");
      out.write("                // 브라우저가 'multipart/form-data'와 경계(boundary)를 자동으로 설정합니다.\n");
      out.write("                body: formData // FormData 객체를 직접 body에 전달\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            const apiResponse = await response.json(); // 응답을 JSON으로 파싱\n");
      out.write("\n");
      out.write("            if (response.ok) { // HTTP 상태 코드가 2xx (성공) 범위인 경우\n");
      out.write("                responseMessageDiv.textContent = apiResponse.message || '작성 성공!';\n");
      out.write("                // 성공 시 리다이렉트 또는 추가 작업 (예: 목록 페이지로 이동)\n");
      out.write("                alert(apiResponse.message || '셀럽 추천 글이 성공적으로 작성되었습니다!');\n");
      out.write("                window.location.href = 'celebList'; // 셀럽 목록 페이지로 이동 (서블릿 URL)\n");
      out.write("            } else {\n");
      out.write("                // HTTP 상태 코드가 4xx 또는 5xx 인 경우\n");
      out.write("                errorMessageDiv.textContent = apiResponse.message || `오류 발생: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${response.statusText}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\n");
      out.write("                console.error('API 응답 오류:', apiResponse);\n");
      out.write("            }\n");
      out.write("        } catch (error) {\n");
      out.write("            console.error('폼 제출 중 오류 발생:', error);\n");
      out.write("            errorMessageDiv.textContent = '네트워크 통신 중 오류가 발생했습니다.';\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
