/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2025-07-01 08:36:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class celebForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>게시글 작성</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("	margin: 40px auto;\r\n");
      out.write("	max-width: 800px;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	background-color: #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], input[type=\"file\"], textarea {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	margin-top: 8px;\r\n");
      out.write("	margin-bottom: 16px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("	font-size: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".editor-block {\r\n");
      out.write("width: 100%;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	padding: 12px;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	margin-bottom: 12px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".editor-block textarea {\r\n");
      out.write("	resize: vertical;\r\n");
      out.write("	min-height: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".editor-block input[type=\"file\"] {\r\n");
      out.write("	background-color: #f4f4f4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-box {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-top: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-box button {\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 1rem;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit-btn {\r\n");
      out.write("	background-color: #e6f0d7;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cancel-btn {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".add-block-btn {\r\n");
      out.write("	display: block;\r\n");
      out.write("	margin: 0 auto 20px;\r\n");
      out.write("	padding: 8px 16px;\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	color: black;\r\n");
      out.write("	border: none;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<h2>셀럽 추천 글 작성</h2>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"submitCelebPost\" method=\"post\"\r\n");
      out.write("		enctype=\"multipart/form-data\">\r\n");
      out.write("		<label>이름</label> <input type=\"text\" name=\"title\" required> <label>설명</label>\r\n");
      out.write("		<input type=\"text\" name=\"desc\" required> <label>썸네일\r\n");
      out.write("			이미지</label> <input type=\"file\" name=\"thumbnail\" accept=\"image/*\">\r\n");
      out.write("\r\n");
      out.write("		<div id=\"editor-area\">\r\n");
      out.write("			<div class=\"editor-block\">\r\n");
      out.write("				<label>텍스트 입력</label>\r\n");
      out.write("				<textarea name=\"contentBlock1_text\"></textarea>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div style=\"text-align: center; margin-bottom: 20px;\">\r\n");
      out.write("			<button type=\"button\" class=\"add-block-btn\"\r\n");
      out.write("				onclick=\"addEditorBlock('text')\">+ 텍스트 블록 추가</button>\r\n");
      out.write("			<button type=\"button\" class=\"add-block-btn\"\r\n");
      out.write("				onclick=\"addEditorBlock('image')\">+ 이미지 블록 추가</button>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"button-box\">\r\n");
      out.write("			<button type=\"submit\" class=\"submit-btn\">작성하기</button>\r\n");
      out.write("			<button type=\"button\" class=\"cancel-btn\" onclick=\"history.back()\">취소</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	let blockCount = 1;\r\n");
      out.write("\r\n");
      out.write("	function addEditorBlock(type) {\r\n");
      out.write("	    blockCount++;\r\n");
      out.write("	    const editorArea = document.getElementById(\"editor-area\");\r\n");
      out.write("\r\n");
      out.write("	    const blockDiv = document.createElement(\"div\");\r\n");
      out.write("	    blockDiv.className = \"editor-block\";\r\n");
      out.write("\r\n");
      out.write("	    if (type === \"text\") {\r\n");
      out.write("	        blockDiv.innerHTML = `\r\n");
      out.write("	            <label>텍스트 입력</label>\r\n");
      out.write("	            <textarea name=\"contentBlock");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${blockCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_text\"></textarea>\r\n");
      out.write("	        `;\r\n");
      out.write("	    } else if (type === \"image\") {\r\n");
      out.write("	        blockDiv.innerHTML = `\r\n");
      out.write("	            <label>이미지 업로드</label>\r\n");
      out.write("	            <input type=\"file\" name=\"contentBlock");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${blockCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_image\" accept=\"image/*\">\r\n");
      out.write("	        `;\r\n");
      out.write("	    } else {\r\n");
      out.write("	        alert(\"알 수 없는 블록 타입입니다.\");\r\n");
      out.write("	        return;\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    editorArea.appendChild(blockDiv);\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
