/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2025-07-01 03:08:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>WITHUS - main</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: 'Arial', sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            background-color: #fff;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        header {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            background-color: #eff7e8;\n");
      out.write("            padding: 2px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #logo img {\n");
      out.write("            width: 200px;\n");
      out.write("            height: auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #search-box {\n");
      out.write("            padding: 8px;\n");
      out.write("            width: 400px;\n");
      out.write("            border: 1px solid #ccc;\n");
      out.write("            position: absolute;\n");
      out.write("            left: 50%;\n");
      out.write("            transform: translateX(-50%);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #logout-btn {\n");
      out.write("            background-color: #e6f0d7;\n");
      out.write("            border: none;\n");
      out.write("            padding: 10px 16px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            width: 90px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        nav {\n");
      out.write("            background-color: #e6f0d7;\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 15px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        nav a {\n");
      out.write("            text-decoration: none;\n");
      out.write("            margin: 0 40px;\n");
      out.write("            color: #000;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        nav a:hover {\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .banner {\n");
      out.write("		    position: relative;\n");
      out.write("		    width: 100%;\n");
      out.write("		    height: 650px;\n");
      out.write("		    overflow: hidden;\n");
      out.write("		    background-color: #ffe04d;\n");
      out.write("		}\n");
      out.write("	\n");
      out.write("		.banner img {\n");
      out.write("		    position: absolute;\n");
      out.write("		    top: 0;\n");
      out.write("		    left: 0;\n");
      out.write("		    width: 100%;\n");
      out.write("		    height: 100%;\n");
      out.write("		    object-fit: cover;\n");
      out.write("		    object-position: center center;\n");
      out.write("		    opacity: 0.8;\n");
      out.write("		    z-index: 1;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        .banner-text {\n");
      out.write("            position: relative;\n");
      out.write("            z-index: 2;\n");
      out.write("            color: #000;\n");
      out.write("            max-width: 800px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .banner-text h2 {\n");
      out.write("            margin: 10px 0;\n");
      out.write("            font-size: 24px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .banner-controls {\n");
      out.write("            position: absolute;\n");
      out.write("            bottom: 10px;\n");
      out.write("            right: 10px;\n");
      out.write("            z-index: 3;\n");
      out.write("            display: flex;\n");
      out.write("            gap: 6px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .banner-controls button {\n");
      out.write("            background-color: rgba(255, 193, 7, 0.9);\n");
      out.write("            border: none;\n");
      out.write("            padding: 6px 8px;\n");
      out.write("            font-size: 14px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            color: #000;\n");
      out.write("            transition: background-color 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .banner-controls button:hover {\n");
      out.write("            background-color: rgba(255, 160, 0, 0.95);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("	      .section-title {\n");
      out.write("		    background-color: #e6f0d7;\n");
      out.write("		    display: flex;\n");
      out.write("		    justify-content: center;\n");
      out.write("		    flex-wrap: wrap;\n");
      out.write("		    gap: 30px;\n");
      out.write("		    padding: 20px 0;\n");
      out.write("		    max-width: 800px;\n");
      out.write("		    margin: 10px auto;  /* 상하 여백 40px */\n");
      out.write("		}\n");
      out.write("\n");
      out.write("\n");
      out.write("        .section-title a {\n");
      out.write("            text-decoration: none;\n");
      out.write("            margin: 0 20px;\n");
      out.write("            color: #000;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .section-title a:hover {\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .main_list {\n");
      out.write("            padding: 20px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .book-list {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 20px;\n");
      out.write("            padding: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .book-item img {\n");
      out.write("            width: 150px;\n");
      out.write("            height: 200px;\n");
      out.write("            object-fit: cover;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<header>\n");
      out.write("    <div id=\"logo\"><img src=\"img/로고.png\"></div>\n");
      out.write("    <input type=\"text\" id=\"search-box\" placeholder=\"검색어를 입력하세요...\" />\n");
      out.write("    <button id=\"logout-btn\" onclick=\"location.href='Logout.jsp'\">로그아웃</button>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<nav>\n");
      out.write("    <a href=\"#\">(AI) 책 추천</a>\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/reviewList\">리뷰</a>\n");
      out.write("    <a href=\"#\">플레이리스트</a>\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/celebList\">셀럽추천</a>\n");
      out.write("    <a href=\"#\">마이페이지</a>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<!-- 🔽 배너 -->\n");
      out.write("<div class=\"banner\">\n");
      out.write("\n");
      out.write("   <!-- 텍스트 -->\n");
      out.write("    <div class=\"banner-text\">\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <!-- 이미지 -->\n");
      out.write("    <img id=\"banner-image\" src=\"img/추천 1.png\" alt=\"배너 이미지\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- 컨트롤 버튼 -->\n");
      out.write("    <div class=\"banner-controls\">\n");
      out.write("        <button onclick=\"prevImage()\">&#9664;</button>\n");
      out.write("        <button onclick=\"toggleSlide()\" id=\"pause-btn\">⏸</button>\n");
      out.write("        <button onclick=\"nextImage()\">&#9654;</button>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 섹션 타이틀 (이미지 바꾸기용 버튼) -->\n");
      out.write("<div class=\"section-title\">\n");
      out.write("    <a href=\"#\" onclick=\"changeBanner('weekly')\">이 주의 책</a>\n");
      out.write("    <a href=\"#\" onclick=\"changeBanner('new')\">신간 소개</a>\n");
      out.write("    <a href=\"#\" onclick=\"changeBanner('featured')\">눈에 띄는 새책</a>\n");
      out.write("    <a href=\"#\" onclick=\"changeBanner('hot')\">화제의 책</a>\n");
      out.write("    <a href=\"#\" onclick=\"changeBanner('exclusive')\">단독 에디션</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 책 목록 -->\n");
      out.write("<div class=\"main_list\">\n");
      out.write("    <h2>돌고 돌아 여름</h2>\n");
      out.write("    <div class=\"book-list\">\n");
      out.write("        <div class=\"book-item\"><img src=\"img/9788970638331.jpg\" alt=\"책1\" /></div>\n");
      out.write("        <div class=\"book-item\"><img src=\"img/급류.png\" alt=\"책2\" /></div>\n");
      out.write("        <div class=\"book-item\"><img src=\"img/고래눈이 내리다.png\" alt=\"책3\" /></div>\n");
      out.write("        <div class=\"book-item\"><img src=\"img/일억 번째 여름.png\" alt=\"책4\" /></div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 스크립트 -->\n");
      out.write("<script>\n");
      out.write("	const bannerImage = document.getElementById(\"banner-image\");\n");
      out.write("\n");
      out.write("    const bannerImages = [\n");
      out.write("        \"img/추천 1.png\",\n");
      out.write("        \"img/추천 2.png\",\n");
      out.write("        \"img/혼모노 추천.jpg\",\n");
      out.write("        \"img/추천 4.png\",\n");
      out.write("        \"img/캘린더.jpg\"\n");
      out.write("    ];\n");
      out.write("\n");
      out.write("    const bannerMap = {\n");
      out.write("        weekly: 1,\n");
      out.write("        new: 2,\n");
      out.write("        featured: 0,\n");
      out.write("        hot: 3,\n");
      out.write("        exclusive: 4\n");
      out.write("    };\n");
      out.write("\n");
      out.write("    let index = 0;\n");
      out.write("    let playing = true;\n");
      out.write("    let interval = setInterval(nextImage, 3000);\n");
      out.write("\n");
      out.write("    function updateImage() {\n");
      out.write("        bannerImage.src = bannerImages[index];\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function nextImage() {\n");
      out.write("        index = (index + 1) % bannerImages.length;\n");
      out.write("        updateImage();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function prevImage() {\n");
      out.write("        index = (index - 1 + bannerImages.length) % bannerImages.length;\n");
      out.write("        updateImage();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function toggleSlide() {\n");
      out.write("        const btn = document.getElementById(\"pause-btn\");\n");
      out.write("        if (playing) {\n");
      out.write("            clearInterval(interval);\n");
      out.write("            btn.textContent = \"▶\";\n");
      out.write("        } else {\n");
      out.write("            interval = setInterval(nextImage, 3000);\n");
      out.write("            btn.textContent = \"⏸\";\n");
      out.write("        }\n");
      out.write("        playing = !playing;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function changeBanner(type) {\n");
      out.write("        if (bannerMap[type] !== undefined) {\n");
      out.write("            index = bannerMap[type];\n");
      out.write("            updateImage();\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
